Update README.md tt
i-keliukh/test_app pull request #1
Opened 2020-06-03 14:35 UTC by i-keliukh

2020-06-05 15:14 UTC, i-keliukh commented
Test 1

2020-06-05 15:15 UTC, i-keliukh commented
Test 2

2020-06-05 15:16 UTC, i-keliukh commented on README.md
> +
Test 3

2020-06-05 15:17 UTC, i-keliukh commented on README.md
> +
Test 4

2020-06-05 15:18 UTC, i-keliukh commented on README.md
> +
Test 5

2020-06-05 15:30 UTC, axxie reviewed
Comment

2020-06-05 15:30 UTC, axxie requested changes
Request changes

2020-06-05 15:30 UTC, axxie approved these changes
Approved

2020-06-05 15:31 UTC, axxie approved these changes

2020-06-10 09:12 UTC, axxie commented
tesst

2020-06-10 09:20 UTC, i-keliukh commented
test

2020-06-10 09:21 UTC, closed without merging